# Code generated by Gemini AI from sample 3D sequence provided (March 2026)
import random
from pathlib import Path

# Standard Amino Acids (3-letter codes)
AMINO_ACIDS = ["ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY", "HIS", "ILE", 
               "LEU", "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL"]

def generate_pdb_line(atom_id, atom_type, res_name, res_id, x, y, z):
    """Formats a single line to the strict PDB standard."""
    return f"ATOM  {atom_id:5d}  {atom_type:<3} {res_name:3} A {res_id:3d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00 20.00           {atom_type[0]}\n"

def generate_synthetic_pdb(filename, num_residues=200):
    Path("data/ingestion").mkdir(parents=True, exist_ok=True)
    atom_id = 1
    x, y, z = 10.0, 10.0, 10.0  # Starting coordinates
    
    with open(f"data/ingestion/{filename}", "w") as f:
        for res_id in range(1, num_residues + 1):
            res_name = random.choice(AMINO_ACIDS)
            # Simulate backbone atoms
            for atom_type in ["N", "CA", "C", "O"]:
                # Incrementally "walk" the coordinates to simulate a chain
                x += random.uniform(-1.5, 1.5)
                y += random.uniform(-1.5, 1.5)
                z += random.uniform(-1.5, 1.5)
                f.write(generate_pdb_line(atom_id, atom_type, res_name, res_id, x, y, z))
                atom_id += 1
        f.write("END\n")

if __name__ == "__main__":
    # Generating 50 sequences (files) to simulate a high-throughput batch
    print(f"🧬 Generating synthetic data of 50 3D PDB files for HelixScale project...")
    for i in range(1, 51):
        generate_synthetic_pdb(f"molecule_{i:03d}.pdb", num_residues=random.randint(100, 500))
    print("✅ Ingestion Layer Ready: data/ingestion/ contains 50 PDB sequences.")